### PR TITLE
Correctly fix the positioning of the iOS 14.2+ time slider

### PR DESCRIPTION
**Pull request by Minh-Ton**
The time slider still doesn't appear on the lock screen with the 1.1 release so I create a pull request again 😅 to fix the positioning of the time slider on iOS 14.2+....

### CODE REVIEW

**Comment by Litteeen** [comment]
it does work for me and others ?

**Comment by Minh-Ton** [comment]
Hmm weird... it doesn't work for me on 14.3...

**Comment by Litteeen** [comment]
i’ll try myself after updating from 14.2

**Comment by Litteeen** [comment]
yep, it's working fine on both 14.2 and 14.3 🌸

**Comment by Minh-Ton** [comment]
Confirmed it working after restoring rootfs and rejailbreak.

**Comment by Litteeen** [comment]
thanks for spending time helping out here 🎀

**Pull request closed without merging**
